controller_list:
  - name: fake_arm_controller
    joints:
      - robot_ur10_shoulder_pan_joint
      - robot_ur10_shoulder_lift_joint
      - robot_ur10_elbow_joint
      - robot_ur10_wrist_1_joint
      - robot_ur10_wrist_2_joint
      - robot_ur10_wrist_3_joint